table _Measures
	lineageTag: 075754bd-1ecb-4243-bc17-60e3533d1566

	/// Get Total Top Domains
	measure __Domains_IsTop = ```
			CALCULATE(Count(Fabric_admin_Domains[id]), Fabric_admin_Domains[parentDomainId]=Blank())+0
				
				
			```
		formatString: 0
		displayFolder: Domains
		lineageTag: 0fce88e9-71e8-4acd-b784-7d06bd6389ff

	/// Get Total Child Domains
	measure __Domains_IsChild = ```
			CALCULATE(Count(Fabric_admin_Domains[id]), Fabric_admin_Domains[parentDomainId]<>Blank())+0
				
			```
		formatString: 0
		displayFolder: Domains
		lineageTag: fc3d1a45-b33a-4b4b-b0ba-95f38cf665e7

	column List
		dataType: string
		isHidden
		lineageTag: 513631cc-9706-4279-a9a3-e7086b574d95
		summarizeBy: none
		sourceColumn: List

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		queryGroup: Measures
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [List = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"List", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

