table Fabric_admin_Domains
	lineageTag: 91dc6b43-2a99-4379-8f6a-1cc0a8868d2c

	column id
		dataType: string
		lineageTag: c9e975a3-d8da-46de-bcc0-9144d80121eb
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column displayName
		dataType: string
		lineageTag: df447fa7-b7bc-47b7-a8c2-bcfe3f21c149
		summarizeBy: none
		sourceColumn: displayName

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 9ee7ffbd-0061-48a5-993c-6ac092825411
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column parentDomainId
		dataType: string
		lineageTag: 7fe9395e-a79c-43a9-9c07-f477c482253e
		summarizeBy: none
		sourceColumn: parentDomainId

		annotation SummarizationSetBy = Automatic

	column contributorsScope
		dataType: string
		lineageTag: f044bdfa-5810-4600-ac58-b4965065f9f0
		summarizeBy: none
		sourceColumn: contributorsScope

		annotation SummarizationSetBy = Automatic

	partition Fabric_admin_Domains = m
		mode: import
		source = ```
				let
				    // Define your tenant ID, client ID, and client secret
				    tenantId = TID,
				    clientId = CID,
				    clientSecret = CS,
				    Scope = "https://analysis.windows.net/powerbi/api/.default",
				    API = "https://api.fabric.microsoft.com/v1/admin",
				    What="domains",
				
				    // Get the access token
				    tokenUrl = "https://login.microsoftonline.com/" & tenantId & "/oauth2/v2.0/token",
				    body = "grant_type=client_credentials&client_id=" & clientId & "&client_secret=" & clientSecret & "&scope=" & Scope,
				    
				    // Make the request to get the token
				    tokenResponse = Json.Document(Web.Contents(tokenUrl, 
				        [
				            Content = Text.ToBinary(body),
				            Headers = [#"Content-Type" = "application/x-www-form-urlencoded"]
				        ])),
				        
				    accessToken = tokenResponse[access_token],
				
				    // Function to get groups with pagination
				    GetGroups = (url) =>
				    let
				
				        // Make the request to get groups
				        GraphResponse = Json.Document(Web.Contents(API, 
				            [
				                Headers = [#"Authorization" = "Bearer " & accessToken],
				                RelativePath = if url<>null then What & "?$top=5000" & Text.Middle(url, Text.PositionOf(url, "&continuationToken=")) else What & "?$top=5000" //null
				                
				            ])),
				        
				        // Get the groups from the response
				        GraphList = Record.FieldOrDefault(GraphResponse, What, null),//GraphResponse[What],
				        
				        // Check if there is a next link for pagination
				        NextLink = Record.FieldOrDefault(GraphResponse, "continuationUri", null),
				        
				        // If there is a next link, recursively get the next page
				        NextGroups = if NextLink <> null then @GetGroups(NextLink) else {}
				    in
				        List.Combine({GraphList,  NextGroups}),
				
				    // Initial call to the function
				    AllGroups = GetGroups(null),
				
				    // Convert the list of groups to a table
				    GraphTable = Table.FromList(AllGroups, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(GraphTable, "Column1", {"id", "displayName", "description", "parentDomainId", "contributorsScope"}, {"id", "displayName", "description", "parentDomainId", "contributorsScope"})
				in
				    #"Expanded Column1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

