table 'Daily Activity Log'
	lineageTag: 8dc1af4c-9f7a-4c66-9170-6b0f55878a22

	column Id
		dataType: string
		lineageTag: ebd8a059-0412-4b3d-bf4c-b37e1e52e28c
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column RecordType
		dataType: string
		lineageTag: f7bafe64-5813-4fc3-9e0e-0f308602e96f
		summarizeBy: none
		sourceColumn: RecordType

		annotation SummarizationSetBy = Automatic

	column CreationTime
		dataType: string
		lineageTag: fdca76c4-0102-4be1-ba9e-aa76e36bacdd
		summarizeBy: none
		sourceColumn: CreationTime

		annotation SummarizationSetBy = Automatic

	column Operation
		dataType: string
		lineageTag: 8e16c8dc-f12d-4623-872e-ee3a07bfcdce
		summarizeBy: none
		sourceColumn: Operation

		annotation SummarizationSetBy = Automatic

	column OrganizationId
		dataType: string
		lineageTag: addb05c7-55cd-4ebe-86b9-46d190b2000d
		summarizeBy: none
		sourceColumn: OrganizationId

		annotation SummarizationSetBy = Automatic

	column UserType
		dataType: string
		lineageTag: c15f451f-0c9e-45fe-b2f0-47cede1c5776
		summarizeBy: none
		sourceColumn: UserType

		annotation SummarizationSetBy = Automatic

	column UserKey
		dataType: string
		lineageTag: c6c6df4e-81f8-44ff-bc0d-2eadd40f30e9
		summarizeBy: none
		sourceColumn: UserKey

		annotation SummarizationSetBy = Automatic

	column Workload
		dataType: string
		lineageTag: 8e46f5a3-b5aa-42aa-8daf-f7fcdd27766c
		summarizeBy: none
		sourceColumn: Workload

		annotation SummarizationSetBy = Automatic

	column ResultStatus
		dataType: string
		lineageTag: 09bca1d7-4558-4dfa-9fe0-0aa8b00b2a35
		summarizeBy: none
		sourceColumn: ResultStatus

		annotation SummarizationSetBy = Automatic

	column UserId
		dataType: string
		lineageTag: 405971f0-9240-489a-8f5d-0a4c083ae641
		summarizeBy: none
		sourceColumn: UserId

		annotation SummarizationSetBy = Automatic

	column ClientIP
		dataType: string
		lineageTag: 0409a078-a956-4d5f-9e19-ece6fba89153
		summarizeBy: none
		sourceColumn: ClientIP

		annotation SummarizationSetBy = Automatic

	column UserAgent
		dataType: string
		lineageTag: fe8bf225-3f2c-41bd-a6e9-8fe8cf8d802c
		summarizeBy: none
		sourceColumn: UserAgent

		annotation SummarizationSetBy = Automatic

	column Activity
		dataType: string
		lineageTag: b325ff52-0e08-4c74-b30c-56304c86d986
		summarizeBy: none
		sourceColumn: Activity

		annotation SummarizationSetBy = Automatic

	column WorkSpaceName
		dataType: string
		lineageTag: 24fa1bd5-fad5-4d56-9c4b-78c6f321e5e3
		summarizeBy: none
		sourceColumn: WorkSpaceName

		annotation SummarizationSetBy = Automatic

	column WorkspaceId
		dataType: string
		lineageTag: b13d567e-766c-4f57-90ef-098f1a085a7b
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column ObjectId
		dataType: string
		lineageTag: 811c5fdf-8fed-45b5-919a-ab28bd8628bd
		summarizeBy: none
		sourceColumn: ObjectId

		annotation SummarizationSetBy = Automatic

	column RequestId
		dataType: string
		lineageTag: 8600d045-bd81-4f76-a652-063807c23bac
		summarizeBy: none
		sourceColumn: RequestId

		annotation SummarizationSetBy = Automatic

	column ObjectType
		dataType: string
		lineageTag: 56ca9d2a-f312-4d28-9850-51ed383e1207
		summarizeBy: none
		sourceColumn: ObjectType

		annotation SummarizationSetBy = Automatic

	column ObjectDisplayName
		dataType: string
		lineageTag: 6fa6a10d-3495-4db0-8453-0c6be814ace0
		summarizeBy: none
		sourceColumn: ObjectDisplayName

		annotation SummarizationSetBy = Automatic

	column Experience
		dataType: string
		lineageTag: c0b5f422-2909-4d8c-a15a-cca886ccc62c
		summarizeBy: none
		sourceColumn: Experience

		annotation SummarizationSetBy = Automatic

	column RefreshEnforcementPolicy
		dataType: string
		lineageTag: cb23fde7-6c31-4360-b607-cb27bac30694
		summarizeBy: none
		sourceColumn: RefreshEnforcementPolicy

		annotation SummarizationSetBy = Automatic

	column IsSuccess
		dataType: string
		lineageTag: c555681e-ce99-4e09-8d4d-214ad61ec403
		summarizeBy: none
		sourceColumn: IsSuccess

		annotation SummarizationSetBy = Automatic

	column ActivityId
		dataType: string
		lineageTag: 464c9b23-649d-4179-afb7-7308ac1e18b3
		summarizeBy: none
		sourceColumn: ActivityId

		annotation SummarizationSetBy = Automatic

	column RequiredWorkspaces
		dataType: string
		lineageTag: d343ad07-096d-4822-b9d4-3575a606331a
		summarizeBy: none
		sourceColumn: RequiredWorkspaces

		annotation SummarizationSetBy = Automatic

	column IncludeSubartifacts
		dataType: string
		lineageTag: 24f0fcb9-66db-478c-8ff0-d053e0b2737a
		summarizeBy: none
		sourceColumn: IncludeSubartifacts

		annotation SummarizationSetBy = Automatic

	column IncludeExpressions
		dataType: string
		lineageTag: c685acc4-580d-45b6-ac15-b4649b4f6953
		summarizeBy: none
		sourceColumn: IncludeExpressions

		annotation SummarizationSetBy = Automatic

	column Lineage
		dataType: string
		lineageTag: c7a4eb91-b121-4c54-943b-b89098b8e8d1
		summarizeBy: none
		sourceColumn: Lineage

		annotation SummarizationSetBy = Automatic

	column DatasourceDetails
		dataType: string
		lineageTag: 180812d2-f6e7-4eb6-b733-4c0129df7c11
		summarizeBy: none
		sourceColumn: DatasourceDetails

		annotation SummarizationSetBy = Automatic

	column ModelsSnapshots
		dataType: string
		lineageTag: 1f29f003-9323-4f83-ac3a-17b02a10b10f
		summarizeBy: none
		sourceColumn: ModelsSnapshots

		annotation SummarizationSetBy = Automatic

	column ExportEventStartDateTimeParameter
		dataType: string
		lineageTag: 43a8beef-5f73-4e1e-98f3-2b64854dd4f0
		summarizeBy: none
		sourceColumn: ExportEventStartDateTimeParameter

		annotation SummarizationSetBy = Automatic

	column ExportEventEndDateTimeParameter
		dataType: string
		lineageTag: 30eee399-f9c8-457f-9ecf-a0783f5c84b5
		summarizeBy: none
		sourceColumn: ExportEventEndDateTimeParameter

		annotation SummarizationSetBy = Automatic

	partition 'Daily Activity Log' = m
		mode: import
		source = ```
				let
				    // Define your tenant ID, client ID, and client secret
				    tenantId = TID,
				    clientId = CID,
				    clientSecret = CS,
				    Scope = "https://analysis.windows.net/powerbi/api/.default",
				    API = "https://api.powerbi.com/v1.0/myorg/admin",
				
				    enddate = DateTime.ToText(Date.EndOfDay(DateTime.FixedLocalNow()), "yyyy-MM-ddTHH:mm:ss.fffZ"),
				    startdt = DateTime.ToText(Date.StartOfDay(DateTime.FixedLocalNow()), "yyyy-MM-ddTHH:mm:ss.fffZ"),
				    tsdate= "startDateTime='"& startdt & "'&endDateTime='" & enddate &"'",
				
				    What="activityevents?",
				
				    // Get the access token
				    tokenUrl = "https://login.microsoftonline.com/" & tenantId & "/oauth2/v2.0/token",
				    body = "grant_type=client_credentials&client_id=" & clientId & "&client_secret=" & clientSecret & "&scope=" & Scope,
				    
				    // Make the request to get the token
				    tokenResponse = Json.Document(Web.Contents(tokenUrl, 
				        [
				            Content = Text.ToBinary(body),
				            Headers = [#"Content-Type" = "application/x-www-form-urlencoded"]
				        ])),
				        
				    accessToken = tokenResponse[access_token],
				
				    // Function to get groups with pagination
				    GetGroups = (url) =>
				    let
				        // Make the request to get groups
				        GraphResponse = Json.Document(Web.Contents(API, 
				            [
				                Headers = [#"Authorization" = "Bearer " & accessToken],
				                RelativePath = if url<>null then What & "?" & Text.Middle(url, Text.PositionOf(url, "continuationToken=")) else What & tsdate //null
				            ])),//,
				        
				        // Get the groups from the response
				        GraphList = GraphResponse[activityEventEntities],
				
				         // Check if there is a next link for pagination
				        NextLink = GraphResponse[continuationUri],
				        
				        // If there is a next link, recursively get the next page
				        NextGroups = if NextLink <> null then @GetGroups(NextLink) else {}
				
				    in
				    List.Combine({GraphList,  NextGroups}),
				
				    // Initial call to the function
				    AllGroups = GetGroups(null),
				
				    // Convert the list of groups to a table
				    GraphTable = Table.FromList(AllGroups, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(GraphTable, "Column1", {"Id", "RecordType", "CreationTime", "Operation", "OrganizationId", "UserType", "UserKey", "Workload", "ResultStatus", "UserId", "ClientIP", "UserAgent", "Activity", "WorkSpaceName", "WorkspaceId", "ObjectId", "RequestId", "ObjectType", "ObjectDisplayName", "Experience", "RefreshEnforcementPolicy", "IsSuccess", "ActivityId", "RequiredWorkspaces", "IncludeSubartifacts", "IncludeExpressions", "Lineage", "DatasourceDetails", "ModelsSnapshots", "ExportEventStartDateTimeParameter", "ExportEventEndDateTimeParameter"}, {"Id", "RecordType", "CreationTime", "Operation", "OrganizationId", "UserType", "UserKey", "Workload", "ResultStatus", "UserId", "ClientIP", "UserAgent", "Activity", "WorkSpaceName", "WorkspaceId", "ObjectId", "RequestId", "ObjectType", "ObjectDisplayName", "Experience", "RefreshEnforcementPolicy", "IsSuccess", "ActivityId", "RequiredWorkspaces", "IncludeSubartifacts", "IncludeExpressions", "Lineage", "DatasourceDetails", "ModelsSnapshots", "ExportEventStartDateTimeParameter", "ExportEventEndDateTimeParameter"}),
				    #"Expanded RequiredWorkspaces" = Table.ExpandListColumn(#"Expanded Column1", "RequiredWorkspaces"),
				    #"Expanded ModelsSnapshots" = Table.ExpandListColumn(#"Expanded RequiredWorkspaces", "ModelsSnapshots"),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded ModelsSnapshots", each true)
				in
				    #"Filtered Rows"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

