table PBI_admin_Workspaces
	lineageTag: e58c8f67-5fcc-4fb2-bc19-f7452ef6ddaa

	column id
		dataType: string
		lineageTag: 865d86d0-6fae-4789-8408-546fb3464df7
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column isReadOnly
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8d623b6b-e97c-4234-9ae2-8e95c613aa9a
		summarizeBy: none
		sourceColumn: isReadOnly

		annotation SummarizationSetBy = Automatic

	column isOnDedicatedCapacity
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6dbee188-32c6-462b-bd9f-7e3c375e4842
		summarizeBy: none
		sourceColumn: isOnDedicatedCapacity

		annotation SummarizationSetBy = Automatic

	column capacityMigrationStatus
		dataType: string
		lineageTag: aedb0eba-8dd1-42b0-abc7-ad3aca3a092d
		summarizeBy: none
		sourceColumn: capacityMigrationStatus

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 50eaf1af-846c-4749-a13f-f63326632a94
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: d3115b55-eef1-4afe-9ce0-13dc27e68c3c
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column 'hasWorkspaceLevelSettings '
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 57a947c5-581b-4bf9-a6ca-7ba24c345bbf
		summarizeBy: none
		sourceColumn: "hasWorkspaceLevelSettings "

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 274ad173-5fc9-41bd-9527-93cdb31ef6fc
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column capacityId
		dataType: string
		lineageTag: 42626219-8486-4ebf-a476-62dad760f9cf
		summarizeBy: none
		sourceColumn: capacityId

		annotation SummarizationSetBy = Automatic

	column defaultDatasetStorageFormat
		dataType: string
		lineageTag: 50713d64-b9c0-4ed9-bc34-267e0ad7fc31
		summarizeBy: none
		sourceColumn: defaultDatasetStorageFormat

		annotation SummarizationSetBy = Automatic

	partition PBI_admin_Workspaces = m
		mode: import
		source = ```
				let
				    // Define your tenant ID, client ID, and client secret
				    tenantId = TID,
				    clientId = CID,
				    clientSecret = CS,
				    Scope = "https://analysis.windows.net/powerbi/api/.default",
				    API = "https://api.powerbi.com/v1.0/myorg/admin",
				    What="groups",
				
				    // Get the access token
				    tokenUrl = "https://login.microsoftonline.com/" & tenantId & "/oauth2/v2.0/token",
				    body = "grant_type=client_credentials&client_id=" & clientId & "&client_secret=" & clientSecret & "&scope=" & Scope,
				    
				    // Make the request to get the token
				    tokenResponse = Json.Document(Web.Contents(tokenUrl, 
				        [
				            Content = Text.ToBinary(body),
				            Headers = [#"Content-Type" = "application/x-www-form-urlencoded"]
				        ])),
				        
				    accessToken = tokenResponse[access_token],
				
				    // Function to get groups with pagination
				    GetGroups = (url) =>
				    let
				
				        // Make the request to get groups
				        GraphResponse = Json.Document(Web.Contents(API, 
				            [
				                Headers = [#"Authorization" = "Bearer " & accessToken],
				                RelativePath = What & "?$top=5000"
				            ]))
				    
				    in
				      GraphResponse[value],
				
				    // Initial call to the function
				    AllGroups = GetGroups(null),
				    // Initial call to the function
				    Workspaces = Table.FromList(AllGroups, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(Workspaces, "Column1", {"id", "isReadOnly", "isOnDedicatedCapacity", "capacityMigrationStatus", "type", "state", "hasWorkspaceLevelSettings ", "name", "capacityId", "defaultDatasetStorageFormat"}, {"id", "isReadOnly", "isOnDedicatedCapacity", "capacityMigrationStatus", "type", "state", "hasWorkspaceLevelSettings ", "name", "capacityId", "defaultDatasetStorageFormat"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"isOnDedicatedCapacity", type logical}, {"isReadOnly", type logical}, {"hasWorkspaceLevelSettings ", type logical}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

